package Programmers.SQL;

public class P_5월식품들의총매출조회하기 {
//    SELECT P.PRODUCT_ID, PRODUCT_NAME, (PRICE * S) AS TOTAL_SALES
//    FROM FOOD_PRODUCT P
//    NATURAL JOIN
//            (SELECT PRODUCT_ID, SUM(AMOUNT) AS S
//    FROM FOOD_ORDER O
//    WHERE PRODUCE_DATE LIKE '2022-05%'
//    GROUP BY PRODUCT_ID) AS O
//    ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC
}
