package Programmers.SQL;

public class P_그룹별조건에맞는식당목록출력하기 {
//    WITH A AS (SELECT MEMBER_ID, COUNT(*) AS C
//    FROM REST_REVIEW
//    GROUP BY MEMBER_ID
//    ORDER BY C DESC
//    LIMIT 1)
//
//    SELECT M.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
//    FROM MEMBER_PROFILE M
//    JOIN (SELECT R.MEMBER_ID, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
//    FROM REST_REVIEW R
//            JOIN
//    A ON R.MEMBER_ID = A.MEMBER_ID) B ON M.MEMBER_ID = B.MEMBER_ID
//    ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC
}
