package SQL;

public class P_경기도에위치한식품창고목록출력하기 {
//    SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') as FREEZER_YN
//    FROM FOOD_WAREHOUSE
//    WHERE WAREHOUSE_NAME LIKE '창고_경기%'
//    ORDER BY WAREHOUSE_ID ASC
}
