package SQL;

public class P_서울에위치한식당목록출력하기 {
//    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, round(avg(REVIEW_SCORE), 2) as SCORE
//    FROM REST_INFO natural join REST_REVIEW
//    WHERE ADDRESS LIKE '서울%'
//    GROUP BY REST_NAME
//    ORDER BY SCORE DESC, FAVORITES DESC
}
